### PR TITLE
fix(azure): Set date range in cost management queries

### LINKED ISSUE #8655: Investigate: Azure billing tables data
From a user (shardulind) report on Discord:

> Recently I came up with weird behaviour while syncing data from azure cost management views (report)
> - I have added custom cost management views for "last7days" , "thisMonth", "thisQuarter"
> - on running sync command, those views are getting fetched in azure_costmanagement_views 
> - but weird thing noticed is in azure_costmanagement_views_queries table,  the properties column is showing data for of this month, despite having parent_id equal to the one in azure_cost_management tables last7days column.
> In short, despite any time range for cost analysis view, the data fetched in azure_costmanagement_views_queries table is for current months billing.
> I tried experimenting with clean setup, and only having one view at a time for (last 7 days), still data being fetched is of monthly billing. 😕

https://discord.com/channels/872925471417962546/873606591335759872/1080201007960703076

### PR DESCRIPTION
**Pull request by disq**
The issue here is, the date range 'presets' supported by the UI don't match 1-1 to the presets in view queries. So we have to check and remedy the problem ourselves.

Fixes #8655

### CODE REVIEW

**Review by erezrokah — APPROVED** [review]

File: plugins/source/azure/resources/services/costmanagement/daterange.go [hunk 1]
```diff
@@ -0,0 +1,93 @@
...
+			m = time.October
+		}
+		return time.Date(t.Year(), m, 1, 0, 0, 0, 0, t.Location())
+	}
+
+	now = now.Truncate(24 * time.Hour)
+
+	switch dr {
+	case "Last7Days":
+		now = now.AddDate(0, 0, -1) // ends yesterday
```
Comment (disq) [inline plugins/source/azure/resources/services/costmanagement/daterange.go:37]: These dates were verified by the Azure console dates for today, at
Screenshot 2023-03-02 at 09 56 27

File: plugins/source/azure/resources/services/costmanagement/view_queries_fetch.go [hunk 2]
```diff
@@ -30,6 +32,17 @@ func fetchViewQueries(ctx context.Context, meta schema.ClientMeta, parent *schem
...
 
+	if (qd.Timeframe == nil || *qd.Timeframe != armcostmanagement.TimeframeTypeCustom) && qd.TimePeriod == nil && item.Properties.DateRange != nil {
+		qd.Timeframe, qd.TimePeriod = dateRangeToTimeFrame(time.Now().UTC(), *item.Properties.DateRange)
+		if qd.Timeframe != nil {
+			cl.Logger().Debug().Any("report_name", item.Name).Str("date_range", *item.Properties.DateRange).Any("resulting_time_period", qd.TimePeriod).Any("resulting_timeframe", qd.Timeframe).Msg("setting time period from date range")
+		}
+	}
+
+	if qd.Timeframe == nil && item.Properties.DateRange != nil {
+		return fmt.Errorf("could not convert date range %q to time period", *item.Properties.DateRange)
```
Comment (disq) [inline plugins/source/azure/resources/services/costmanagement/view_queries_fetch.go:43]: If we don't know about this date range we simply refuse fetching incorrect data.
