### PR TITLE
fix: Downgrade provider

### LINKED ISSUE #496: provider downgrade doesn't work
`cloudquery provider downgrade [provider]` will not work:
- if `config.hcl` contains the current provider version, it will exit with `no change`
- if `config.hcl` contains the provider version we want to downgrade to, down migrations from the future (from the version we're currently at) don't exist yet, so migrate fails

Maybe downgrade should first take/upgrade to `latest` for the provider, then downgrade to the specified (in config) version.

related #378

### PR DESCRIPTION
**Pull request by disq**
Closes #496.

This is extra bad, but given the way everything is set up this is what I ended up with.

### CODE REVIEW

File: pkg/ui/console/client.go [hunk 1]
```diff
@@ -407,28 +407,60 @@ func (c Client) UpgradeProviders(ctx context.Context, args []string) error {
...
+
+	provVersions := make(map[string]string, len(providers))
+	for _, p := range providers {
+		provVersions[p.Name] = p.Version
+		p.Version = migrator.Latest
+	}
+
+	newCfg := *c.cfg
+	newCfg.CloudQuery.Providers = providers
+	conWithLatest, err := CreateClientFromConfig(ctx, &newCfg)
```
Comment (roneli) [inline pkg/ui/console/client.go:431]: wouldn't conWithLatest (version X > Y) be able to downgrade Y -> Z  (Y > Z) I don't think we need to do an upgrade with the cqWithLatest.

**Review by roneli — CHANGES_REQUESTED** [review]
Looks okay, I think we can avoid the extra upgrade, but fix me if I am incorrect in my assumption.

File: pkg/ui/console/client.go (hunk 1 above)
Comment (disq) [reply pkg/ui/console/client.go:429]: Fixed
