### PR TITLE
fix(digitalocean): Re-add missing resources: Load Balancers and Regions

### LINKED ISSUE #10561: bug: Digitalocean source is missing Load Balancers
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

DigitalOcean source is missing Load Balancers (after the sdk v2 [upgrade](https://github.com/cloudquery/cloudquery/pull/1794)) as reported in [Discord](https://discord.com/channels/872925471417962546/873606591335759872/1103424624764657674)

### Expected Behavior

Load Balancer resources should be fetched

### CloudQuery (redacted) config

```yaml
```

### Steps To Reproduce

_No response_

### CloudQuery (redacted) logs

```
```

### CloudQuery version

Recent

### Additional Context

_No response_

### Pull request (optional)

- [X] I can submit a pull request

### PR DESCRIPTION
**Pull request by disq**
Fixes #10561

### CODE REVIEW

File: plugins/source/digitalocean/resources/services/load_balancers/load_balancers.go [hunk 1]
```diff
@@ -0,0 +1,50 @@
...
+
+	"github.com/cloudquery/cloudquery/plugins/source/digitalocean/client"
+	"github.com/cloudquery/plugin-sdk/v2/schema"
+	"github.com/cloudquery/plugin-sdk/v2/transformers"
+	"github.com/digitalocean/godo"
+)
+
+func LoadBalancers() *schema.Table {
+	return &schema.Table{
+		Name:      "digitalocean_load_balancers",
```
Comment (hermanschaaf) [inline plugins/source/digitalocean/resources/services/load_balancers/load_balancers.go:14]: Can we add a description with a link to this table (and the others?)

**Review by hermanschaaf — APPROVED** [review]
Table descriptions would be a nice addition, but otherwise LGTM 👍
