### PR TITLE
fix: Purge command failure

### LINKED ISSUE #805: Purge Command Not Working Properly
### Describe the Bug
Unable to purge data
running the following results in an error
`cloudquery --config=/app/config/config.hcl provider purge aws --last-update=24h -dry-run=false `

### Expected Behavior
should drop all data older than 24 hours

### CloudQuery Version

```
computer@Bens-MBP cloudquery % cloudquery version
Version: 0.24.1
Commit: c996fb6950e1332f1fad43e762126a3cc1b97870
Date: 2022-05-26T17:09:16Z
```
### Debug Output

```
{"level":"info","instance_id":"20d453a6-2aeb-4e0e-971b-33cfbd7a5935","time":"2022-05-27T16:33:37-04:00","message":"Purge for providers [aws] failed"}
```

### PR DESCRIPTION
**Pull request by roneli**
It would print fail although there isn't any error diags, moreover the diags are not printed in the end of the execution.

Closes #805

🎉 Thank you for making CloudQuery awesome by submitting a PR 🎉

#### Summary

---

Use the following steps to ensure your PR is ready to be reviewed

- [x] Read the [contribution guidelines](../blob/main/.github/CONTRIBUTING.md) 🧑‍🎓
- [x] Run `go fmt` to format your code 🖊
- [x] Lint your changes via `golangci-lint run` 🚨 (install golangci-lint [here](https://golangci-lint.run/usage/install/#local-installation))
- [x] Update or add tests 🧪
- [x] Ensure the status checks below are successful ✅

### CODE REVIEW

File: pkg/ui/console/client.go [hunk 1]
```diff
@@ -340,7 +341,7 @@ func (c Client) RemoveStaleData(ctx context.Context, lastUpdate time.Duration, d
 			ui.ColorizedOutput(ui.ColorWarning, "\t%s: %d resources\n\n", r, result.AffectedResources[r])
 		}
 	}
-	if !diags.HasErrors() {
+	if diags.HasErrors() {
```
Comment (erezrokah) [inline pkg/ui/console/client.go:344]: 🥇

**Review by erezrokah — APPROVED** [review]

**Review by disq — APPROVED** [review]
