### PR TITLE
fix(aws-resources)!: Query issue on `aws_cloudwatchlogs_log_group_data_protection_policies`

### LINKED ISSUE #10216: bug: GetDataProtectionPolicy for aws_cloudwatchlogs_log_group_data_protection_policies causes ValidationException error
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

[GetDataProtectionPolicy ](https://docs.aws.amazon.com/AmazonCloudWatchLogs/latest/APIReference/API_GetDataProtectionPolicy.html)for aws_cloudwatchlogs_log_group_data_protection_policies causes ValidationException error because log group arns end with :* and the allowed pattern for logGroupIdentifier for GetDataProtectionPolicy  is `[\w#+=/:,.@-]*` which doesn't allow * 

This seems like an AWS bug but could be fixed by stripping the trailing * from the log group arn.

### Expected Behavior

No ValidationException when GetDataProtectionPolicy called

### CloudQuery (redacted) config

```
```

### Steps To Reproduce

_No response_

### CloudQuery (redacted) logs

```json
{
    "level": "error",
    "module": "aws-src",
    "client": "************:us-east-2",
    "error": "operation error CloudWatch Logs: GetDataProtectionPolicy, https response error StatusCode: 400, RequestID: 53f1c155-a3f5-44bd-a6c2-ec93e711991e, api error ValidationException: 1 validation error detected: Value 'arn:aws:logs:us-east-2:***********:log-group:<log-group-name-redacted>:*' at 'logGroupIdentifier' failed to satisfy constraint: Member must satisfy regular expression pattern: [\\w#+=/:,.@-]*",
    "message": "table resolver finished with error",
    "table": "aws_cloudwatchlogs_log_group_data_protection_policies",
    "time": "2023-04-19T08:23:40Z"
}
```

### CloudQuery version

2.5.3

### Additional Context

AWS plugin v.16.2.0
Postgres plugin v3.0.3

### Pull request (optional)

- [ ] I can submit a pull request

### PR DESCRIPTION
**Pull request by disq**
Closes #10216

### CODE REVIEW

File: plugins/source/aws/resources/services/cloudwatchlogs/data_protection_policies.go [hunk 1]
```diff
@@ -34,8 +34,13 @@ func dataProtectionPolicy() *schema.Table {
 	}
 }
 func fetchDataProtectionPolicy(ctx context.Context, meta schema.ClientMeta, parent *schema.Resource, res chan<- any) error {
+	lg := parent.Item.(types.LogGroup)
+	if lg.DataProtectionStatus == "" { // Inactive Data Protection policy, don't attempt to fetch
```
Comment (disq) [inline plugins/source/aws/resources/services/cloudwatchlogs/data_protection_policies.go:38]: `DataProtectionStatus` is empty for groups without data protection set, and also the Get query comes up empty, which breaks the Primary Key.

File: plugins/source/aws/resources/services/cloudwatchlogs/data_protection_policies.go [hunk 2]
```diff
@@ -17,7 +17,7 @@ func dataProtectionPolicy() *schema.Table {
 		Description: `https://docs.aws.amazon.com/AmazonCloudWatchLogs/latest/APIReference/API_GetDataProtectionPolicy.html`,
 		Resolver:    fetchDataProtectionPolicy,
 		Multiplex:   client.ServiceAccountRegionMultiplexer(tableName, "logs"),
-		Transform:   transformers.TransformWithStruct(&cloudwatchlogs.GetDataProtectionPolicyOutput{}, transformers.WithPrimaryKeys("LogGroupIdentifier"), transformers.WithSkipFields("ResultMetadata")),
+		Transform:   transformers.TransformWithStruct(&cloudwatchlogs.GetDataProtectionPolicyOutput{}, transformers.WithSkipFields("ResultMetadata")),
```
Comment (disq) [inline plugins/source/aws/resources/services/cloudwatchlogs/data_protection_policies.go:20]: No need for double PKs, and also `LogGroupIdentifier` has a tendency to come up empty, it could also come empty for deleted/archived data protection entries, we simply don't know.

**Review by hermanschaaf — APPROVED** [review]

**Review by bbernays — APPROVED** [review]
