### PR TITLE
fix(gcp): Re-add gcp_iam_service_account_keys

### LINKED ISSUE #1990: Bug(v1): gcp_iam_service_account_keys is missing
Previously fetched with `Projects.ServiceAccounts.Keys.List`.

### PR DESCRIPTION
**Pull request by disq**
Closes #1990

### CODE REVIEW

File: plugins/source/gcp/codegen/recipes/iam.go [hunk 1]
```diff
@@ -9,10 +9,8 @@ import (
 
 var iamResources = []*Resource{
 	{
-		SubService:   "roles",
-		Struct:       &iam.Role{},
-		NewFunction:  iam.NewProjectsRolesService,
-		ListFunction: (&iam.ProjectsRolesService{}).List,
```
Comment (yevgenypats) [inline plugins/source/gcp/codegen/recipes/iam.go:15]: Is this not used ?

**Review by yevgenypats — APPROVED** [review]
Looks good. had one question.

File: plugins/source/gcp/codegen/recipes/iam.go (hunk 1 above)
Comment (disq) [reply plugins/source/gcp/codegen/recipes/iam.go:15]: > Is this not used ?

@yevgenypats because `SkipFetch` is set to true on all resources below.
