### PR TITLE
fix(aws): Fix logger in aws_fsx_file_caches

### LINKED ISSUE #4806: bug: Some log lines showing in the CLI (without --log-console)
Unless specified otherwise, all logs should go to the log file.

 ```
cloudquery sync aws.yml
Loading spec(s) from aws.yml
Starting migration for: aws -> [postgresql]
Migration completed successfully.
Starting sync for:  aws -> [postgresql]
{"level":"warn","error":"operation error FSx: DescribeFileCaches, https response error StatusCode: 400, RequestID: 9d87156c-e844-4e71-9948-388a7dc07228, BadRequest: The requested feature is not enabled for this AWS account.","time":"2022-11-18T16:07:16Z","message":"skipping resource"}
| Syncing resources... (29316/-, 1318 resources/s) [2m18s] {"level":"warn","error":"operation error FSx: DescribeFileCaches, https response error StatusCode: 400, RequestID: 26380483-76ea-4412-8b18-b1811b031f37, BadRequest: The requested feature is not enabled for this AWS account.","time":"2022-11-18T16:07:20Z","message":"skipping resource"}
| Syncing resources... (35214/-, 1651 resources/s) [2m21s] {"level":"warn","error":"operation error FSx: DescribeFileCaches, https response error StatusCode: 400, RequestID: a3aa79eb-ef31-46c4-bdbd-e561adc0d153, BadRequest: The requested feature is not enabled for this AWS account.","time":"2022-11-18T16:07:23Z","message":"skipping resource"}
- Syncing resources... (40403/-, 1779 resources/s) [2m24s]
```

This may be specific to the AWS source plugin, I'm not sure.

### PR DESCRIPTION
**Pull request by disq**
Fixes #4806 

The problem was, resource wasn't using the client's logger. No other resource in the repo seems to have this problem.

### CODE REVIEW

File: plugins/source/aws/resources/services/fsx/file_caches_fetch.go [hunk 1]
```diff
@@ -23,7 +22,7 @@ func fetchFsxFileCaches(ctx context.Context, meta schema.ClientMeta, parent *sch
 		if err != nil {
 			var ae smithy.APIError
 			if errors.As(err, &ae) && ae.ErrorCode() == "BadRequest" && ae.ErrorMessage() == "The requested feature is not enabled for this AWS account." {
-				log.Warn().Err(err).Msg("skipping resource")
+				cl.Logger().Warn().Err(err).Msg("skipping resource")
```
Comment (yevgenypats) [inline plugins/source/aws/resources/services/fsx/file_caches_fetch.go:25]: maybe just returning the error? this way it will have consistent logging from the SDK?

Comment (disq) [reply plugins/source/aws/resources/services/fsx/file_caches_fetch.go]: Done @yevgenypats
